/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FinalizarCompraRouteImport } from './routes/finalizar-compra'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as NuevaColeccionRouteImport } from './routes/nueva-coleccion'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as PoliticasDePrivacidadRouteImport } from './routes/politicas-de-privacidad'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as PedidoReferenceRouteImport } from './routes/pedido.$reference'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalizarCompraRoute = FinalizarCompraRouteImport.update({
  id: '/finalizar-compra',
  path: '/finalizar-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaColeccionRoute = NuevaColeccionRouteImport.update({
  id: '/nueva-coleccion',
  path: '/nueva-coleccion',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasDePrivacidadRoute = PoliticasDePrivacidadRouteImport.update({
  id: '/politicas-de-privacidad',
  path: '/politicas-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoReferenceRoute = PedidoReferenceRouteImport.update({
  id: '/pedido/$reference',
  path: '/pedido/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/finalizar-compra': typeof FinalizarCompraRoute
  '/nosotros': typeof NosotrosRoute
  '/nueva-coleccion': typeof NuevaColeccionRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/politicas-de-privacidad': typeof PoliticasDePrivacidadRoute
  '/tienda': typeof TiendaRoute
  '/pedido/$reference': typeof PedidoReferenceRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/finalizar-compra': typeof FinalizarCompraRoute
  '/nosotros': typeof NosotrosRoute
  '/nueva-coleccion': typeof NuevaColeccionRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/politicas-de-privacidad': typeof PoliticasDePrivacidadRoute
  '/tienda': typeof TiendaRoute
  '/pedido/$reference': typeof PedidoReferenceRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/finalizar-compra': typeof FinalizarCompraRoute
  '/nosotros': typeof NosotrosRoute
  '/nueva-coleccion': typeof NuevaColeccionRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/politicas-de-privacidad': typeof PoliticasDePrivacidadRoute
  '/tienda': typeof TiendaRoute
  '/pedido/$reference': typeof PedidoReferenceRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/finalizar-compra'
    | '/nosotros'
    | '/nueva-coleccion'
    | '/pedido-confirmado'
    | '/politicas-de-privacidad'
    | '/tienda'
    | '/pedido/$reference'
    | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/finalizar-compra'
    | '/nosotros'
    | '/nueva-coleccion'
    | '/pedido-confirmado'
    | '/politicas-de-privacidad'
    | '/tienda'
    | '/pedido/$reference'
    | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/finalizar-compra'
    | '/nosotros'
    | '/nueva-coleccion'
    | '/pedido-confirmado'
    | '/politicas-de-privacidad'
    | '/tienda'
    | '/pedido/$reference'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  FinalizarCompraRoute: typeof FinalizarCompraRoute
  NosotrosRoute: typeof NosotrosRoute
  NuevaColeccionRoute: typeof NuevaColeccionRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  PoliticasDePrivacidadRoute: typeof PoliticasDePrivacidadRoute
  TiendaRoute: typeof TiendaRoute
  PedidoReferenceRoute: typeof PedidoReferenceRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalizar-compra': {
      id: '/finalizar-compra'
      path: '/finalizar-compra'
      fullPath: '/finalizar-compra'
      preLoaderRoute: typeof FinalizarCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-coleccion': {
      id: '/nueva-coleccion'
      path: '/nueva-coleccion'
      fullPath: '/nueva-coleccion'
      preLoaderRoute: typeof NuevaColeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas-de-privacidad': {
      id: '/politicas-de-privacidad'
      path: '/politicas-de-privacidad'
      fullPath: '/politicas-de-privacidad'
      preLoaderRoute: typeof PoliticasDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$reference': {
      id: '/pedido/$reference'
      path: '/pedido/$reference'
      fullPath: '/pedido/$reference'
      preLoaderRoute: typeof PedidoReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  FinalizarCompraRoute: FinalizarCompraRoute,
  NosotrosRoute: NosotrosRoute,
  NuevaColeccionRoute: NuevaColeccionRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  PoliticasDePrivacidadRoute: PoliticasDePrivacidadRoute,
  TiendaRoute: TiendaRoute,
  PedidoReferenceRoute: PedidoReferenceRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
